import { Toaster } from '@/components/ui/toaster'
import { WhatsAppButton } from '@/components/WhatsAppButton'
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Footer } from './components/NextFooter'
import { Navigation } from './components/NextNavigation'
import './globals.css'
import { Providers } from './providers'

export const metadata: Metadata = {
	title: 'Clerk Next.js Quickstart',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body>
					<Providers>
						<div className='min-h-screen bg-white dark:bg-slate-950 transition-colors duration-300'>
							<header>
								<SignedOut>
									<SignInButton />
									<SignUpButton />
								</SignedOut>
								<SignedIn>
									<UserButton />
								</SignedIn>
							</header>
							<Navigation />
							{children}
							<Footer />
							<WhatsAppButton />
							<Toaster />
						</div>
					</Providers>
				</body>
			</html>
		</ClerkProvider>
	)
}
